### ISSUE TITLE
Access Violation due to incorrect calling convention being used (__cdecl instead of __stdcall)

### ISSUE THREAD

**Issue by const-volatile** [Altenius/j2534-rs#3]
J2534 uses the WinAPI convention. It is defined in Windows header files as `WINAPI`, which is in turn defined using the Win32 declarator `__stdcall`. To make this crate work correctly the function pointer definitions in `"j2534-0.1.2\src\cpp\j2534.cpp`" need to be modified accordingly.

i.e. `typedef int32_t (*PassThruOpen_t)(void *, uint32_t *);` need to be changed to
`typedef int32_t (WINAPI *PassThruOpen_t)(void *, uint32_t *);`

**Comment by jcmnn** [comment]
There's another branch that uses libloading instead of compiling a C wrapper, but it would crash when calling into the J2534 DLL I was using. I wonder if the calling convention is the problem there.

**Comment by const-volatile** [comment]
Yes, calling convention is most likely the problem there as well.
