### ISSUE TITLE
Use extern "stdcall" fn

### ISSUE THREAD

**Issue by rnd-ash** [Altenius/j2534-rs#6]
Hi there,

I'm the author of OVD (https://github.com/rnd-ash/OpenVehicleDiag), and wrote a similar J2534 API based on some of your work (Except I'm also unofficially supporting UNIX / OSX).

I found that using `extern "C" fn` and `extern "system" fn` causes issues with the i686-pc-windows-msvc target (ACCESS_VIOLATION error being triggered). Changing the function calls to `extern "stdcall" fn` fixes the issue

**Comment by jcmnn** [comment]
That project sounds interesting! Thanks for the tip.
